### ISSUE TITLE
ICR not reliable - what can I do?

### ISSUE THREAD

**Issue by BusyBonsai** [ACSPRI/queXF#2]
Hello there
I downloaded your three KBs for numbers, small letters and capital letters, uploaded them to my quexf setup, and assigned them to questionnaires. However, in verification view, only numbers are being read / suggested - unfortunately with a rather poor success rate ("1706201934" is being read as "7706751774"). 
Prior I tried training ICR myself with 400 instances (as suggested in quexf documentation) of each number from 1-9, but that was even worse; it read the above number as "4444444444".

ICR for letters/text doesnt seem to work at all for me - their is no suggestion, fields in verification view are empty for me to type in what I think was written. It is single letters though.

Any idea how to improve ICR?

Kind Regards

**Comment by adamzammit** [comment]
Can you share your ICR KB XML file that was generated?

I haven't maintained this code in a while as we haven't used it in production for a while. Even when we got it pretty close to accurate we found that our verification operators spent just as much or more time fixing minor errors which were hard to spot rather than keying in handwritten fields.

**Comment by BusyBonsai** [comment]
Dear Adam

Thanks for your help. You can find the xml in the zip file attached.
[icr_kb_1_to_9.zip](https://github.com/ACSPRI/queXF/files/3310992/icr_kb_1_to_9.zip)


> Even when we got it pretty close to accurate we found that our verification operators spent just as much or more time fixing minor errors which were hard to spot rather than keying in handwritten fields.

That is an interesting finding. Does that apply to your experience with both numbers and letters ICR?

**Comment by adamzammit** [comment]
Thanks for that file. Overall it looks ok, so I'm not sure why you are getting such poor results after training with your own data set. I'm not sure how much time you want to spend on this - but if you are able to share your queXF database after training occurred I could look further to see for anything that stands out.

Regarding our finding - yes this applies to both fields. I think if the numbers ICR was augmented with a list of expected responses or some other validation, then this could be a valuable automated tool - but for responses that are always variable then we would leave it disabled.

**Comment by BusyBonsai** [comment]
Dear Adam
I am sorry for the late answer. Considering your assessment of ICR minor errors overhead we now decided to not pursue this feature further. Thank you very much though for your efforts and good service!
Regards
Adam ;)
