### ISSUE TITLE
Page is not aligned properly

### ISSUE THREAD

**Issue by alex-pl** [ACSPRI/queXF#4]
When testing my form with `Test form compatibility with queXF` (`pagetest.php`) the page edges are correctly detected.
Then, when verifying a form using `verifyjs.php` the page is not aligned correctly.
I've used the same PDF in both cases.

The page edges are not detected OR they are detected but the page is not aligned accordingly when verifying. This causes the fields being misplaced and verifying is very hard and error-prone.

Is this maybe a known issue, could it be a bad configuration or does someone maybe have an idea what I could change or test?

**Comment by adamzammit** [comment]
Hi Alex,

Can you please confirm that the scan and the original are of the same page size? 

Adam

**Comment by alex-pl** [comment]
Hi Adam,

thank you for the quick reply!

I'm using a form exported with LimeSurvey. I've uploaded the original PDF and the original banding XML to queXF to set up the form.

For testing and verifying I'm using a scanned PDF which is the printed LimeSurvey-generated PDF, filled in by the participant and scanned.

The original is 21,01 x 29,71 cm
The scan is 21 x 29,7 cm

The scan is slightly smaller and minimally rotated with changing degrees by the feed mechanism of the scanner:

Original:
<img width="1078" alt="Bildschirmfoto 2020-06-22 um 12 07 53" src="https://user-images.githubusercontent.com/4785458/85276239-c826fa80-b481-11ea-9818-922c700bb74f.png">

Scan (the blue box is only in the screenshot for anonymization):
<img width="1079" alt="Bildschirmfoto 2020-06-22 um 12 07 38" src="https://user-images.githubusercontent.com/4785458/85276253-cb21eb00-b481-11ea-9540-8f5202f5c9b7.png">

Shouldn't the alignment feature detect the edges and align the page edges automatically to compensate for the small differences during the scan?
As said, when testing the scanned PDF, the page edges are detected properly.

Thanks, Alex

**Comment by adamzammit** [comment]
Yes the alignment feature should sort this out.

One thing to test is going to the "page setup" function and then clicking on "Page setup disabled (click to enable)" then once that has processed, click on "Page setup ENABLED (click to disable)" - this resets the page boundaries and can sometimes fix this issue.

Otherwise - can you please send the PDF generated by LimeSurvey/queXML along with the banding XML along with a (de identified) scan that exhibits this error and I'll look into it.

Adam

**Comment by alex-pl** [comment]
You were right, this solved the issue!
This was really easy to fix, thanks again for your great support! :)

If I'm doing any code changes, e.g. improvements in the area of the LimeSurvey integration, I'll definitely look into giving back and contribute the code.
